"""Every generated artefact. Nothing here is hand-edited, and check 7 verifies
that what is committed matches what this module would produce.
"""

from __future__ import annotations

import html
import subprocess
from pathlib import Path

from markdown_it import MarkdownIt
from markdown_it.common.utils import escapeHtml
from mdit_py_plugins.dollarmath import dollarmath_plugin

from .model import REPO, Corpus, Objects, load_corpus, load_objects

BANNER = (
    "<!-- Generated by scripts/build_site.py from notation/objects.yaml.\n"
    "     Do not edit. Edit objects.yaml and rebuild. -->\n"
)


def _esc(text: str) -> str:
    """Escape author-supplied text for HTML. Titles and preambles are prose from a
    mathematical corpus, so "PD < 1%" is ordinary rather than exotic, and this
    repo is public.
    """
    return html.escape(str(text), quote=True)


def _dot_label(text: str) -> str:
    """A DOT label is a quoted string, so a double quote in a title would end it
    early. Backslash first, or the escapes escape each other.
    """
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _render_math(content: str, env: dict) -> str:
    """dollarmath's own renderer escapes the TeX and wraps it in a bare
    `<span>` or `<div>`, with no delimiter characters left in the text at all,
    so KaTeX's auto-render extension would have nothing to match against. Put
    back `\\(...\\)` for inline and `\\[...\\]` for display: both are already
    among auto-render's built-in delimiters, so nothing downstream needs to
    change to recognise them.
    """
    escaped = escapeHtml(content)
    return f"\\[{escaped}\\]" if env["display_mode"] else f"\\({escaped}\\)"


# One module-level renderer, reused by every node page. `html=False` closes a
# finding deferred from Task 7: MarkdownIt()'s default is html=True, so a
# recognised raw HTML tag in a node body would reach a public page verbatim.
# dollarmath tokenises `$...$` and `$$...$$` ahead of CommonMark's escape
# handling, so a thin space such as `\,` survives inside maths where plain
# CommonMark would read the backslash as escaping a comma and drop it.
MD = MarkdownIt("commonmark", {"html": False}).use(dollarmath_plugin, renderer=_render_math)


def render_symbols(objects: Objects) -> str:
    lines = [
        BANNER,
        "# Symbol table",
        "",
        "One meaning per object. A domain keeps its own notation, so the same object",
        "appears under several symbols and a reader crossing domains can see which",
        "spellings refer to the same thing.",
        "",
    ]
    for obj in sorted(objects.by_id.values(), key=lambda o: o.id):
        lines += [
            f"## {obj.name}",
            "",
            f"`{obj.id}`, canonically ${obj.canonical}$. {obj.definition}",
            "",
            "| Domain | Symbol | Called | Note |",
            "|---|---|---|---|",
        ]
        for alias in obj.aliases:
            lines.append(
                f"| {alias.domain} | ${alias.symbol}$ | {alias.name} "
                f"| {alias.note or ''} |"
            )
        lines.append("")
    return "\n".join(lines)


HEAD = """<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="stylesheet" href="{css}">
</head><body>
"""

# Node pages carry three extra asset tags path and index pages do not need,
# so they get their own head rather than widening the shared HEAD above.
# Vendored, not inlined: a node page sits in a published tree of roughly 500
# pages at Phase 3 scale, and inlining KaTeX's ~630 kB into every one of them
# would be a poor trade for the one-off cost a lecture already pays to be a
# self-contained, emailable artefact. One shared copy under vendor/katex/,
# reached with a relative link, keeps every node page free of any network
# call while paying for the library once rather than five hundred times.
NODE_HEAD = """<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="stylesheet" href="{css}">
<link rel="stylesheet" href="../../vendor/katex/katex.min.css">
<script src="../../vendor/katex/katex.min.js"></script>
<script src="../../vendor/katex/auto-render.min.js"></script>
</head><body>
"""

# dollarmath consumes every `$` while it tokenises the body, so none survive
# into the rendered page: `_render_math` re-wraps the surviving TeX in
# `\(...\)` and `\[...\]` instead. Restricting auto-render to exactly those
# two delimiters, rather than its full default list, keeps it from misreading
# a stray currency `$` elsewhere in a node's prose (an LGD or exposure figure,
# say) as the start of a `$$...$$` display block.
NODE_MATH_SCRIPT = (
    "<script>renderMathInElement(document.body, {delimiters: "
    r'[{left: "\\(", right: "\\)", display: false}, '
    r'{left: "\\[", right: "\\]", display: true}]});</script>' "\n"
)


def _plural(count: int, word: str) -> str:
    """One node reads oddly as "1 nodes", and Phase 1 starts most paths from a
    single node.
    """
    return f"{count} {word}" if count == 1 else f"{count} {word}s"


def render_index(corpus: Corpus) -> str:
    rows = []
    for path in sorted(corpus.paths.values(), key=lambda p: p.id):
        rows.append(
            f'<li><a href="site/paths/{_esc(path.id)}.html">{_esc(path.title)}</a> '
            f"<span>{_plural(len(path.nodes), 'node')}</span></li>"
        )
    taught = sum(1 for n in corpus.nodes.values() if n.taught_in)
    return (
        HEAD.format(title="Alchemist", css="assets/lecture.css")
        + "<h1>Alchemist</h1>\n"
        + f"<p>{_plural(len(corpus.nodes), 'node')}, {taught} of them taught in full, "
        + f"across {_plural(len(corpus.paths), 'path')}.</p>\n"
        + "<ul>\n" + "\n".join(rows) + "\n</ul>\n</body></html>\n"
    )


def render_path_page(path, corpus: Corpus) -> str:
    rows = []
    for node_id in path.nodes:
        node = corpus.nodes[node_id]
        lecture = (
            f' <a href="../../lectures/{_esc(node.taught_in)}.html">lecture</a>'
            if node.taught_in else ""
        )
        rows.append(
            f'<li><a href="../nodes/{_esc(node.id)}.html">{_esc(node.title)}</a>{lecture}</li>'
        )
    return (
        HEAD.format(title=_esc(path.title), css="../../assets/lecture.css")
        + f"<h1>{_esc(path.title)}</h1>\n<p>{_esc(path.preamble)}</p>\n"
        + "<ol>\n" + "\n".join(rows) + "\n</ol>\n</body></html>\n"
    )


# Path pages live in site/paths/ and node pages in site/nodes/, so a path page
# reaches a node page as ../nodes/<id>.html. Keep the two directories siblings.


def render_node_page(node, corpus: Corpus, objects: Objects) -> str:
    """A tier-1 page: the author's three written sections, then three generated
    tails. Splitting it this way is what keeps a Phase 3 agent's job to three
    short pieces of prose, and it means the alias table, the unlocks list and
    the sources can never fall out of step with the graph.
    """
    parts = [
        NODE_HEAD.format(title=_esc(node.title), css="../../assets/lecture.css"),
        f"<h1>{_esc(node.title)}</h1>",
        MD.render(node.body),
    ]

    if len({s.domain for s in node.spends}) > 1:
        rows = []
        for spend in node.spends:
            alias = objects.by_id[spend.object].for_domain(spend.domain)
            # alias.symbol is deliberately not passed through _esc: it is TeX
            # destined for KaTeX, not HTML destined for a reader, and escaping
            # it would hand the renderer "&#x5C;mu_x" instead of "\mu_x". It
            # comes from notation/objects.yaml, reviewed repo content rather
            # than arbitrary author input, and check 1 already constrains what
            # a node may spend. Wrapping it the same way `_render_math` wraps
            # body maths, rather than adding bare `$...$` to the auto-render
            # delimiters below, means a stray currency `$` in a node's prose
            # still can't be misread as a display block.
            rows.append(
                f"<tr><td>{_esc(spend.domain)}</td>"
                f'<td><span class="math inline">\\({alias.symbol}\\)</span></td>'
                f"<td>{_esc(alias.name)}</td></tr>"
            )
        parts += [
            "<h2>Called in each domain</h2>",
            "<table><thead><tr><th>Domain</th><th>Symbol</th><th>Called</th>"
            "</tr></thead><tbody>" + "".join(rows) + "</tbody></table>",
        ]

    unlocks = sorted(o.id for o in corpus.nodes.values() if node.id in o.requires)
    if unlocks:
        links = "".join(f'<li><a href="{_esc(u)}.html">{_esc(u)}</a></li>' for u in unlocks)
        parts += ["<h2>What this unlocks</h2>", f"<ul>{links}</ul>"]

    if node.vault_articles or node.vault_sources:
        items = "".join(
            f"<li>{_esc(ref)}</li>" for ref in (*node.vault_articles, *node.vault_sources)
        )
        parts += ["<h2>Sources</h2>", f"<ul>{items}</ul>"]

    return "\n".join(parts) + "\n" + NODE_MATH_SCRIPT + "</body></html>\n"


def render_domain_dot(corpus: Corpus, domain: str) -> str:
    """One graph per domain. An edge is drawn only where both ends sit in the
    domain, so a domain view stays readable rather than dragging in every root.
    """
    members = {n.id for n in corpus.nodes.values() if domain in n.domains}
    lines = [
        "digraph alchemist {",
        '  rankdir=LR; node [shape=box, fontname="Helvetica", fontsize=10];',
    ]
    for node_id in sorted(members):
        label = _dot_label(corpus.nodes[node_id].title)
        lines.append(f'  "{node_id}" [label="{label}"];')
    for node_id in sorted(members):
        for required in sorted(corpus.nodes[node_id].requires):
            if required in members:
                lines.append(f'  "{required}" -> "{node_id}";')
    lines.append("}")
    return "\n".join(lines) + "\n"


def build(root: Path = REPO) -> list[Path]:
    """Write every generated artefact and return what was written."""
    corpus, objects = load_corpus(root), load_objects(root)
    written: list[Path] = []

    symbols = root / "notation" / "symbols.md"
    symbols.write_text(render_symbols(objects))
    written.append(symbols)

    index = root / "index.html"
    index.write_text(render_index(corpus))
    written.append(index)

    pages = root / "site" / "paths"
    pages.mkdir(parents=True, exist_ok=True)
    for path in corpus.paths.values():
        target = pages / f"{path.id}.html"
        target.write_text(render_path_page(path, corpus))
        written.append(target)

    node_pages = root / "site" / "nodes"
    node_pages.mkdir(parents=True, exist_ok=True)
    for node in corpus.nodes.values():
        target = node_pages / f"{node.id}.html"
        target.write_text(render_node_page(node, corpus, objects))
        written.append(target)

    graphs = root / "site" / "graphs"
    graphs.mkdir(parents=True, exist_ok=True)
    domains = {d for n in corpus.nodes.values() for d in n.domains}
    for domain in sorted(domains):
        svg = graphs / f"{domain}.svg"
        try:
            subprocess.run(
                ["dot", "-Tsvg", "-o", str(svg)],
                input=render_domain_dot(corpus, domain), text=True, check=True,
            )
        except FileNotFoundError as exc:
            raise FileNotFoundError(
                "graphviz is not on PATH, so the domain graphs cannot be drawn. "
                "Install it, for example with `brew install graphviz`."
            ) from exc
        written.append(svg)
    return written
