"""Every generated artefact. Nothing here is hand-edited, and check 7 verifies
that what is committed matches what this module would produce.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from markdown_it import MarkdownIt

from .model import REPO, Corpus, Objects, load_corpus, load_objects

BANNER = (
    "<!-- Generated by scripts/build_site.py from notation/objects.yaml.\n"
    "     Do not edit. Edit objects.yaml and rebuild. -->\n"
)


def render_symbols(objects: Objects) -> str:
    lines = [
        BANNER,
        "# Symbol table",
        "",
        "One meaning per object. A domain keeps its own notation, so the same object",
        "appears under several symbols and a reader crossing domains can see which",
        "spellings refer to the same thing.",
        "",
    ]
    for obj in sorted(objects.by_id.values(), key=lambda o: o.id):
        lines += [
            f"## {obj.name}",
            "",
            f"`{obj.id}`, canonically ${obj.canonical}$. {obj.definition}",
            "",
            "| Domain | Symbol | Called | Note |",
            "|---|---|---|---|",
        ]
        for alias in obj.aliases:
            lines.append(
                f"| {alias.domain} | ${alias.symbol}$ | {alias.name} "
                f"| {alias.note or ''} |"
            )
        lines.append("")
    return "\n".join(lines)


HEAD = """<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="stylesheet" href="{css}">
</head><body>
"""


def render_index(corpus: Corpus) -> str:
    rows = []
    for path in sorted(corpus.paths.values(), key=lambda p: p.id):
        rows.append(
            f'<li><a href="paths/{path.id}.html">{path.title}</a> '
            f"<span>{len(path.nodes)} nodes</span></li>"
        )
    taught = sum(1 for n in corpus.nodes.values() if n.taught_in)
    return (
        HEAD.format(title="Alchemist", css="assets/lecture.css")
        + "<h1>Alchemist</h1>\n"
        + f"<p>{len(corpus.nodes)} nodes, {taught} of them taught in full, "
        + f"across {len(corpus.paths)} paths.</p>\n"
        + "<ul>\n" + "\n".join(rows) + "\n</ul>\n</body></html>\n"
    )


def render_path_page(path, corpus: Corpus) -> str:
    rows = []
    for node_id in path.nodes:
        node = corpus.nodes[node_id]
        lecture = (
            f' <a href="../lectures/{node.taught_in}.html">lecture</a>'
            if node.taught_in else ""
        )
        rows.append(
            f'<li><a href="../nodes/{node.id}.html">{node.title}</a>{lecture}</li>'
        )
    return (
        HEAD.format(title=path.title, css="../assets/lecture.css")
        + f"<h1>{path.title}</h1>\n<p>{path.preamble}</p>\n"
        + "<ol>\n" + "\n".join(rows) + "\n</ol>\n</body></html>\n"
    )


# Path pages live in site/paths/ and node pages in site/nodes/, so a path page
# reaches a node page as ../nodes/<id>.html. Keep the two directories siblings.


def render_node_page(node, corpus: Corpus, objects: Objects) -> str:
    """A tier-1 page: the author's three written sections, then three generated
    tails. Splitting it this way is what keeps a Phase 3 agent's job to three
    short pieces of prose, and it means the alias table, the unlocks list and
    the sources can never fall out of step with the graph.
    """
    parts = [
        HEAD.format(title=node.title, css="../assets/lecture.css"),
        f"<h1>{node.title}</h1>",
        MarkdownIt().render(node.body),
    ]

    if len({s.domain for s in node.spends}) > 1:
        rows = []
        for spend in node.spends:
            alias = objects.by_id[spend.object].for_domain(spend.domain)
            rows.append(
                f"<tr><td>{spend.domain}</td><td>${alias.symbol}$</td>"
                f"<td>{alias.name}</td></tr>"
            )
        parts += [
            "<h2>Called in each domain</h2>",
            "<table><thead><tr><th>Domain</th><th>Symbol</th><th>Called</th>"
            "</tr></thead><tbody>" + "".join(rows) + "</tbody></table>",
        ]

    unlocks = sorted(o.id for o in corpus.nodes.values() if node.id in o.requires)
    if unlocks:
        links = "".join(f'<li><a href="{u}.html">{u}</a></li>' for u in unlocks)
        parts += ["<h2>What this unlocks</h2>", f"<ul>{links}</ul>"]

    if node.vault_articles or node.vault_sources:
        items = "".join(
            f"<li>{ref}</li>" for ref in (*node.vault_articles, *node.vault_sources)
        )
        parts += ["<h2>Sources</h2>", f"<ul>{items}</ul>"]

    return "\n".join(parts) + "\n</body></html>\n"


def render_domain_dot(corpus: Corpus, domain: str) -> str:
    """One graph per domain. An edge is drawn only where both ends sit in the
    domain, so a domain view stays readable rather than dragging in every root.
    """
    members = {n.id for n in corpus.nodes.values() if domain in n.domains}
    lines = [
        "digraph alchemist {",
        '  rankdir=LR; node [shape=box, fontname="Helvetica", fontsize=10];',
    ]
    for node_id in sorted(members):
        lines.append(f'  "{node_id}" [label="{corpus.nodes[node_id].title}"];')
    for node_id in sorted(members):
        for required in sorted(corpus.nodes[node_id].requires):
            if required in members:
                lines.append(f'  "{required}" -> "{node_id}";')
    lines.append("}")
    return "\n".join(lines) + "\n"


def build(root: Path = REPO) -> list[Path]:
    """Write every generated artefact and return what was written."""
    corpus, objects = load_corpus(root), load_objects(root)
    written: list[Path] = []

    symbols = root / "notation" / "symbols.md"
    symbols.write_text(render_symbols(objects))
    written.append(symbols)

    index = root / "index.html"
    index.write_text(render_index(corpus))
    written.append(index)

    pages = root / "site" / "paths"
    pages.mkdir(parents=True, exist_ok=True)
    for path in corpus.paths.values():
        target = pages / f"{path.id}.html"
        target.write_text(render_path_page(path, corpus))
        written.append(target)

    node_pages = root / "site" / "nodes"
    node_pages.mkdir(parents=True, exist_ok=True)
    for node in corpus.nodes.values():
        target = node_pages / f"{node.id}.html"
        target.write_text(render_node_page(node, corpus, objects))
        written.append(target)

    graphs = root / "site" / "graphs"
    graphs.mkdir(parents=True, exist_ok=True)
    domains = {d for n in corpus.nodes.values() for d in n.domains}
    for domain in sorted(domains):
        svg = graphs / f"{domain}.svg"
        subprocess.run(
            ["dot", "-Tsvg", "-o", str(svg)],
            input=render_domain_dot(corpus, domain), text=True, check=True,
        )
        written.append(svg)
    return written
