"""Every generated artefact. Nothing here is hand-edited, and check 7 verifies
that what is committed matches what this module would produce.
"""

from __future__ import annotations

from .model import Objects

BANNER = (
    "<!-- Generated by scripts/build_site.py from notation/objects.yaml.\n"
    "     Do not edit. Edit objects.yaml and rebuild. -->\n"
)


def render_symbols(objects: Objects) -> str:
    lines = [
        BANNER,
        "# Symbol table",
        "",
        "One meaning per object. A domain keeps its own notation, so the same object",
        "appears under several symbols and a reader crossing domains can see which",
        "spellings refer to the same thing.",
        "",
    ]
    for obj in sorted(objects.by_id.values(), key=lambda o: o.id):
        lines += [
            f"## {obj.name}",
            "",
            f"`{obj.id}`, canonically ${obj.canonical}$. {obj.definition}",
            "",
            "| Domain | Symbol | Called | Note |",
            "|---|---|---|---|",
        ]
        for alias in obj.aliases:
            lines.append(
                f"| {alias.domain} | ${alias.symbol}$ | {alias.name} "
                f"| {alias.note or ''} |"
            )
        lines.append("")
    return "\n".join(lines)
